# Generated by Django 5.2.8 on 2025-11-18 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pijama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del pijama')),
                ('descripcion', models.TextField(help_text='Describe las características del pijama', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('imagen', models.ImageField(help_text='Sube una imagen del pijama', upload_to='pijamas/', verbose_name='Imagen del pijama')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Pijama',
                'verbose_name_plural': 'Pijamas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
